/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#c3c0ff",
        "surface-tint": "#4d44e3",
        "on-background": "#191c1e",
        "primary": "#3525cd",
        "tertiary-fixed-dim": "#ffb695",
        "inverse-on-surface": "#eff1f3",
        "tertiary": "#7e3000",
        "surface-container-high": "#e6e8ea",
        "tertiary-container": "#a44100",
        "surface-container": "#eceef0",
        "outline": "#777587",
        "on-tertiary-fixed-variant": "#7b2f00",
        "primary-fixed-dim": "#c3c0ff",
        "primary-container": "#4f46e5",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "on-tertiary-container": "#ffd2be",
        "error-container": "#ffdad6",
        "primary-fixed": "#e2dfff",
        "on-secondary-fixed": "#0b1c30",
        "surface-container-low": "#f2f4f6",
        "on-error-container": "#93000a",
        "background": "#f7f9fb",
        "on-surface-variant": "#464555",
        "secondary-fixed-dim": "#b7c8e1",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "on-primary-container": "#dad7ff",
        "surface-variant": "#e0e3e5",
        "outline-variant": "#c7c4d8",
        "on-error": "#ffffff",
        "secondary": "#505f76",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#54647a",
        "secondary-container": "#d0e1fb",
        "tertiary-fixed": "#ffdbcc",
        "error": "#ba1a1a",
        "on-primary-fixed": "#0f0069",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "surface": "#f7f9fb",
        "on-primary-fixed-variant": "#3323cc",
        "on-tertiary-fixed": "#351000",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3133",
        "secondary-fixed": "#d3e4fe"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
    },
  },
  plugins: [],
}
